import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Stage",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../components/theme-provider";
import { LoadingOverlayProvider } from "../components/loading-overlay-provider";
import { Toaster } from "../components/ui/sonner";
import { Suspense } from "react";

export default function Layout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider>
          <LoadingOverlayProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <main>
                {children}
              </main>
            </Suspense>
            <Toaster />
          </LoadingOverlayProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
