import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../components/theme-provider";
import { LoadingOverlayProvider } from "../components/loading-overlay-provider";
import { Toaster } from "../components/ui/sonner";

export default function Layout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider>
          <LoadingOverlayProvider>
            <main>
              {children}
            </main>
            <Toaster />
          </LoadingOverlayProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
